uuid = "2da26df0-0925-4091-a0e6-919fee5381f9"
name = "Audio August"
homepage = "https://www.inexor.org/"
maintainers = [
    "Johannes 'Hanni' Schneider"
]
description = "Audioaugust is a collection of sound effects, noises and sound loops with the goal to extend the use of sound in Inexor. Inexor is a free multi-platform open source game which is a fork from the Cube 2: Sauerbraten game."
categories = [
]
